/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockQuickSwapRouterInterface extends Interface {
    getFunction(nameOrSignature: "EXCHANGE_RATE" | "WETH" | "addLiquidity" | "factory" | "fundRouter" | "getAmountIn" | "getAmountOut" | "getAmountsIn" | "getAmountsOut" | "quote" | "removeLiquidity" | "swapETHForExactTokens" | "swapExactETHForTokens" | "swapExactTokensForETH" | "swapExactTokensForTokens" | "swapTokensForExactETH" | "swapTokensForExactTokens"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'EXCHANGE_RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundRouter', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAmountIn', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAmountOut', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAmountsIn', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getAmountsOut', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'quote', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapETHForExactTokens', values: [BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactETHForTokens', values: [BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactTokensForETH', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactTokensForTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapTokensForExactETH', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapTokensForExactTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'EXCHANGE_RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountsIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountsOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapETHForExactTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactETHForTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTokensForExactETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTokensForExactTokens', data: BytesLike): Result;
  }

  

  export interface MockQuickSwapRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockQuickSwapRouter;
    waitForDeployment(): Promise<this>;

    interface: MockQuickSwapRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    EXCHANGE_RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fundRouter: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAmountIn: TypedContractMethod<
      [amountOut: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getAmountOut: TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getAmountsIn: TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >
    

    
    getAmountsOut: TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >
    

    
    quote: TypedContractMethod<
      [amountA: BigNumberish, reserveA: BigNumberish, reserveB: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >
    

    
    swapETHForExactTokens: TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'payable'
    >
    

    
    swapExactETHForTokens: TypedContractMethod<
      [amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'payable'
    >
    

    
    swapExactTokensForETH: TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    swapExactTokensForTokens: TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    swapTokensForExactETH: TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    swapTokensForExactTokens: TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'EXCHANGE_RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fundRouter'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAmountIn'): TypedContractMethod<
      [amountOut: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountOut'): TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountsIn'): TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountsOut'): TypedContractMethod<
      [amountIn: BigNumberish, path: AddressLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'quote'): TypedContractMethod<
      [amountA: BigNumberish, reserveA: BigNumberish, reserveB: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapETHForExactTokens'): TypedContractMethod<
      [amountOut: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'payable'
    >;
getFunction(nameOrSignature: 'swapExactETHForTokens'): TypedContractMethod<
      [amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'payable'
    >;
getFunction(nameOrSignature: 'swapExactTokensForETH'): TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapExactTokensForTokens'): TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapTokensForExactETH'): TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapTokensForExactTokens'): TypedContractMethod<
      [amountOut: BigNumberish, amountInMax: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }