/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IQuickSwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IQuickSwapRouter__factory>
getContractFactory(name: 'ISomiArbVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISomiArbVault__factory>
getContractFactory(name: 'IStandardCLOB', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStandardCLOB__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockQuickSwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockQuickSwapRouter__factory>
getContractFactory(name: 'MockStandardCLOB', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockStandardCLOB__factory>
getContractFactory(name: 'SomiArbVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SomiArbVault__factory>

  getContractAt(name: 'IQuickSwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IQuickSwapRouter>
getContractAt(name: 'ISomiArbVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISomiArbVault>
getContractAt(name: 'IStandardCLOB', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStandardCLOB>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockQuickSwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockQuickSwapRouter>
getContractAt(name: 'MockStandardCLOB', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockStandardCLOB>
getContractAt(name: 'SomiArbVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SomiArbVault>

  deployContract(name: 'IQuickSwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IQuickSwapRouter>
deployContract(name: 'ISomiArbVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISomiArbVault>
deployContract(name: 'IStandardCLOB', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStandardCLOB>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockQuickSwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockQuickSwapRouter>
deployContract(name: 'MockStandardCLOB', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockStandardCLOB>
deployContract(name: 'SomiArbVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SomiArbVault>

  deployContract(name: 'IQuickSwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IQuickSwapRouter>
deployContract(name: 'ISomiArbVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISomiArbVault>
deployContract(name: 'IStandardCLOB', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStandardCLOB>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockQuickSwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockQuickSwapRouter>
deployContract(name: 'MockStandardCLOB', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockStandardCLOB>
deployContract(name: 'SomiArbVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SomiArbVault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  