/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iQuickSwapRouterSol from './IQuickSwapRouter.sol/index.js';
export type { iQuickSwapRouterSol };
import type * as iSomiArbVaultSol from './ISomiArbVault.sol/index.js';
export type { iSomiArbVaultSol };
import type * as iStandardClobSol from './IStandardCLOB.sol/index.js';
export type { iStandardClobSol };