/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ISomiArbVault {
      
    export type ArbitrageParamsStruct = {tokenA: AddressLike, tokenB: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, expectedProfit: BigNumberish, minProfit: BigNumberish, slippage: BigNumberish, buyPlatform: BigNumberish, sellPlatform: BigNumberish, deadline: BigNumberish}

    export type ArbitrageParamsStructOutput = [tokenA: string, tokenB: string, amountIn: bigint, minAmountOut: bigint, expectedProfit: bigint, minProfit: bigint, slippage: bigint, buyPlatform: bigint, sellPlatform: bigint, deadline: bigint] & {tokenA: string, tokenB: string, amountIn: bigint, minAmountOut: bigint, expectedProfit: bigint, minProfit: bigint, slippage: bigint, buyPlatform: bigint, sellPlatform: bigint, deadline: bigint }
  

    export type RiskParametersInputStruct = {maxPositionSize: BigNumberish, maxDailyVolume: BigNumberish, exposureLimit: BigNumberish, cooldownPeriod: BigNumberish}

    export type RiskParametersInputStructOutput = [maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint] & {maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint }
  
    }

export declare namespace SomiArbVault {
      
    export type ArbitrageExecutionStruct = {timestamp: BigNumberish, tokenA: AddressLike, tokenB: AddressLike, amountIn: BigNumberish, profitGenerated: BigNumberish, buyPlatform: BigNumberish, sellPlatform: BigNumberish, gasUsed: BigNumberish, successful: boolean}

    export type ArbitrageExecutionStructOutput = [timestamp: bigint, tokenA: string, tokenB: string, amountIn: bigint, profitGenerated: bigint, buyPlatform: bigint, sellPlatform: bigint, gasUsed: bigint, successful: boolean] & {timestamp: bigint, tokenA: string, tokenB: string, amountIn: bigint, profitGenerated: bigint, buyPlatform: bigint, sellPlatform: bigint, gasUsed: bigint, successful: boolean }
  

    export type PerformanceMetricsStruct = {totalProfit: BigNumberish, totalTrades: BigNumberish, successfulTrades: BigNumberish, totalVolume: BigNumberish, lastProfitTimestamp: BigNumberish, sharpeRatio: BigNumberish, maxDrawdown: BigNumberish}

    export type PerformanceMetricsStructOutput = [totalProfit: bigint, totalTrades: bigint, successfulTrades: bigint, totalVolume: bigint, lastProfitTimestamp: bigint, sharpeRatio: bigint, maxDrawdown: bigint] & {totalProfit: bigint, totalTrades: bigint, successfulTrades: bigint, totalVolume: bigint, lastProfitTimestamp: bigint, sharpeRatio: bigint, maxDrawdown: bigint }
  

    export type VaultConfigStruct = {managementFee: BigNumberish, performanceFee: BigNumberish, minProfitThreshold: BigNumberish, maxSlippage: BigNumberish, autoCompound: boolean, feeRecipient: AddressLike}

    export type VaultConfigStructOutput = [managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint, autoCompound: boolean, feeRecipient: string] & {managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint, autoCompound: boolean, feeRecipient: string }
  
    }

  export interface SomiArbVaultInterface extends Interface {
    getFunction(nameOrSignature: "EMERGENCY_WINDOW" | "MAX_BPS" | "MAX_MANAGEMENT_FEE" | "MAX_PERFORMANCE_FEE" | "MAX_SLIPPAGE" | "MIN_PROFIT_THRESHOLD" | "arbitrageHistory" | "authorizedAgents" | "config" | "deposit" | "emergencyState" | "emergencyWithdraw" | "executeArbitrage" | "getArbitrageExecution" | "getPerformanceMetrics" | "getTotalValue" | "getUserBalance" | "getUserShares" | "owner" | "paused" | "performance" | "quickSwapRouter" | "renounceOwnership" | "resolveEmergency" | "riskParams" | "setAgentAuthorization" | "setSupportedToken" | "standardCLOB" | "supportedTokens" | "totalDeposits" | "transferOwnership" | "triggerEmergency" | "updateConfig" | "updateRiskParameters" | "userDeposits" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentAuthorized" | "ArbitrageExecuted" | "ConfigUpdated" | "Deposit" | "EmergencyResolved" | "EmergencyTriggered" | "OwnershipTransferred" | "Paused" | "ProfitDistributed" | "RiskParametersUpdated" | "Unpaused" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'EMERGENCY_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MANAGEMENT_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PERFORMANCE_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SLIPPAGE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_PROFIT_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'arbitrageHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'authorizedAgents', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'config', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyState', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeArbitrage', values: [ISomiArbVault.ArbitrageParamsStruct]): string;
encodeFunctionData(functionFragment: 'getArbitrageExecution', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPerformanceMetrics', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserBalance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserShares', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'performance', values?: undefined): string;
encodeFunctionData(functionFragment: 'quickSwapRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveEmergency', values?: undefined): string;
encodeFunctionData(functionFragment: 'riskParams', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAgentAuthorization', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setSupportedToken', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'standardCLOB', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportedTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalDeposits', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'triggerEmergency', values: [string]): string;
encodeFunctionData(functionFragment: 'updateConfig', values: [SomiArbVault.VaultConfigStruct]): string;
encodeFunctionData(functionFragment: 'updateRiskParameters', values: [ISomiArbVault.RiskParametersInputStruct]): string;
encodeFunctionData(functionFragment: 'userDeposits', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'EMERGENCY_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MANAGEMENT_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PERFORMANCE_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SLIPPAGE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_PROFIT_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arbitrageHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'config', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeArbitrage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArbitrageExecution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPerformanceMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'performance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quickSwapRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveEmergency', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'riskParams', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAgentAuthorization', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSupportedToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'standardCLOB', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'triggerEmergency', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateRiskParameters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AgentAuthorizedEvent {
      export type InputTuple = [agent: AddressLike, authorized: boolean];
      export type OutputTuple = [agent: string, authorized: boolean];
      export interface OutputObject {agent: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArbitrageExecutedEvent {
      export type InputTuple = [tokenA: AddressLike, tokenB: AddressLike, amountIn: BigNumberish, profit: BigNumberish, buyPlatform: BigNumberish, sellPlatform: BigNumberish, executionId: BigNumberish];
      export type OutputTuple = [tokenA: string, tokenB: string, amountIn: bigint, profit: bigint, buyPlatform: bigint, sellPlatform: bigint, executionId: bigint];
      export interface OutputObject {tokenA: string, tokenB: string, amountIn: bigint, profit: bigint, buyPlatform: bigint, sellPlatform: bigint, executionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConfigUpdatedEvent {
      export type InputTuple = [managementFee: BigNumberish, performanceFee: BigNumberish, minProfitThreshold: BigNumberish, maxSlippage: BigNumberish];
      export type OutputTuple = [managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint];
      export interface OutputObject {managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, amount: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, token: string, amount: bigint, shares: bigint];
      export interface OutputObject {user: string, token: string, amount: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyResolvedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyTriggeredEvent {
      export type InputTuple = [trigger: AddressLike, reason: string, timestamp: BigNumberish];
      export type OutputTuple = [trigger: string, reason: string, timestamp: bigint];
      export interface OutputObject {trigger: string, reason: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfitDistributedEvent {
      export type InputTuple = [token: AddressLike, totalProfit: BigNumberish, managementFee: BigNumberish, performanceFee: BigNumberish, userShare: BigNumberish];
      export type OutputTuple = [token: string, totalProfit: bigint, managementFee: bigint, performanceFee: bigint, userShare: bigint];
      export interface OutputObject {token: string, totalProfit: bigint, managementFee: bigint, performanceFee: bigint, userShare: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RiskParametersUpdatedEvent {
      export type InputTuple = [maxPositionSize: BigNumberish, maxDailyVolume: BigNumberish, exposureLimit: BigNumberish, cooldownPeriod: BigNumberish];
      export type OutputTuple = [maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint];
      export interface OutputObject {maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, amount: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, token: string, amount: bigint, shares: bigint];
      export interface OutputObject {user: string, token: string, amount: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SomiArbVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): SomiArbVault;
    waitForDeployment(): Promise<this>;

    interface: SomiArbVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    EMERGENCY_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MANAGEMENT_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PERFORMANCE_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SLIPPAGE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_PROFIT_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    arbitrageHistory: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {timestamp: bigint, tokenA: string, tokenB: string, amountIn: bigint, profitGenerated: bigint, buyPlatform: bigint, sellPlatform: bigint, gasUsed: bigint, successful: boolean }],
      'view'
    >
    

    
    authorizedAgents: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    config: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, string] & {managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint, autoCompound: boolean, feeRecipient: string }],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    emergencyState: TypedContractMethod<
      [],
      [[boolean, bigint, string, string] & {isEmergency: boolean, emergencyTimestamp: bigint, emergencyTrigger: string, emergencyReason: string }],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executeArbitrage: TypedContractMethod<
      [params: ISomiArbVault.ArbitrageParamsStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    getArbitrageExecution: TypedContractMethod<
      [executionId: BigNumberish, ],
      [SomiArbVault.ArbitrageExecutionStructOutput],
      'view'
    >
    

    
    getPerformanceMetrics: TypedContractMethod<
      [],
      [SomiArbVault.PerformanceMetricsStructOutput],
      'view'
    >
    

    
    getTotalValue: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserBalance: TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserShares: TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    performance: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {totalProfit: bigint, totalTrades: bigint, successfulTrades: bigint, totalVolume: bigint, lastProfitTimestamp: bigint, sharpeRatio: bigint, maxDrawdown: bigint }],
      'view'
    >
    

    
    quickSwapRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveEmergency: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    riskParams: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint }],
      'view'
    >
    

    
    setAgentAuthorization: TypedContractMethod<
      [agent: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setSupportedToken: TypedContractMethod<
      [token: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    standardCLOB: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportedTokens: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    totalDeposits: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    triggerEmergency: TypedContractMethod<
      [reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateConfig: TypedContractMethod<
      [newConfig: SomiArbVault.VaultConfigStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateRiskParameters: TypedContractMethod<
      [params: ISomiArbVault.RiskParametersInputStruct, ],
      [void],
      'nonpayable'
    >
    

    
    userDeposits: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [token: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'EMERGENCY_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MANAGEMENT_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PERFORMANCE_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SLIPPAGE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_PROFIT_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'arbitrageHistory'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {timestamp: bigint, tokenA: string, tokenB: string, amountIn: bigint, profitGenerated: bigint, buyPlatform: bigint, sellPlatform: bigint, gasUsed: bigint, successful: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedAgents'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'config'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, string] & {managementFee: bigint, performanceFee: bigint, minProfitThreshold: bigint, maxSlippage: bigint, autoCompound: boolean, feeRecipient: string }],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyState'): TypedContractMethod<
      [],
      [[boolean, bigint, string, string] & {isEmergency: boolean, emergencyTimestamp: bigint, emergencyTrigger: string, emergencyReason: string }],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeArbitrage'): TypedContractMethod<
      [params: ISomiArbVault.ArbitrageParamsStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getArbitrageExecution'): TypedContractMethod<
      [executionId: BigNumberish, ],
      [SomiArbVault.ArbitrageExecutionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPerformanceMetrics'): TypedContractMethod<
      [],
      [SomiArbVault.PerformanceMetricsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalValue'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBalance'): TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserShares'): TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'performance'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {totalProfit: bigint, totalTrades: bigint, successfulTrades: bigint, totalVolume: bigint, lastProfitTimestamp: bigint, sharpeRatio: bigint, maxDrawdown: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'quickSwapRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveEmergency'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'riskParams'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {maxPositionSize: bigint, maxDailyVolume: bigint, exposureLimit: bigint, cooldownPeriod: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setAgentAuthorization'): TypedContractMethod<
      [agent: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSupportedToken'): TypedContractMethod<
      [token: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'standardCLOB'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportedTokens'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalDeposits'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'triggerEmergency'): TypedContractMethod<
      [reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateConfig'): TypedContractMethod<
      [newConfig: SomiArbVault.VaultConfigStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateRiskParameters'): TypedContractMethod<
      [params: ISomiArbVault.RiskParametersInputStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userDeposits'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [token: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'AgentAuthorized'): TypedContractEvent<AgentAuthorizedEvent.InputTuple, AgentAuthorizedEvent.OutputTuple, AgentAuthorizedEvent.OutputObject>;
getEvent(key: 'ArbitrageExecuted'): TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
getEvent(key: 'ConfigUpdated'): TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'EmergencyResolved'): TypedContractEvent<EmergencyResolvedEvent.InputTuple, EmergencyResolvedEvent.OutputTuple, EmergencyResolvedEvent.OutputObject>;
getEvent(key: 'EmergencyTriggered'): TypedContractEvent<EmergencyTriggeredEvent.InputTuple, EmergencyTriggeredEvent.OutputTuple, EmergencyTriggeredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProfitDistributed'): TypedContractEvent<ProfitDistributedEvent.InputTuple, ProfitDistributedEvent.OutputTuple, ProfitDistributedEvent.OutputObject>;
getEvent(key: 'RiskParametersUpdated'): TypedContractEvent<RiskParametersUpdatedEvent.InputTuple, RiskParametersUpdatedEvent.OutputTuple, RiskParametersUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'AgentAuthorized(address,bool)': TypedContractEvent<AgentAuthorizedEvent.InputTuple, AgentAuthorizedEvent.OutputTuple, AgentAuthorizedEvent.OutputObject>;
      AgentAuthorized: TypedContractEvent<AgentAuthorizedEvent.InputTuple, AgentAuthorizedEvent.OutputTuple, AgentAuthorizedEvent.OutputObject>;
    

      'ArbitrageExecuted(address,address,uint256,uint256,uint8,uint8,uint256)': TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
      ArbitrageExecuted: TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
    

      'ConfigUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
      ConfigUpdated: TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
    

      'Deposit(address,address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'EmergencyResolved(uint256)': TypedContractEvent<EmergencyResolvedEvent.InputTuple, EmergencyResolvedEvent.OutputTuple, EmergencyResolvedEvent.OutputObject>;
      EmergencyResolved: TypedContractEvent<EmergencyResolvedEvent.InputTuple, EmergencyResolvedEvent.OutputTuple, EmergencyResolvedEvent.OutputObject>;
    

      'EmergencyTriggered(address,string,uint256)': TypedContractEvent<EmergencyTriggeredEvent.InputTuple, EmergencyTriggeredEvent.OutputTuple, EmergencyTriggeredEvent.OutputObject>;
      EmergencyTriggered: TypedContractEvent<EmergencyTriggeredEvent.InputTuple, EmergencyTriggeredEvent.OutputTuple, EmergencyTriggeredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProfitDistributed(address,uint256,uint256,uint256,uint256)': TypedContractEvent<ProfitDistributedEvent.InputTuple, ProfitDistributedEvent.OutputTuple, ProfitDistributedEvent.OutputObject>;
      ProfitDistributed: TypedContractEvent<ProfitDistributedEvent.InputTuple, ProfitDistributedEvent.OutputTuple, ProfitDistributedEvent.OutputObject>;
    

      'RiskParametersUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<RiskParametersUpdatedEvent.InputTuple, RiskParametersUpdatedEvent.OutputTuple, RiskParametersUpdatedEvent.OutputObject>;
      RiskParametersUpdated: TypedContractEvent<RiskParametersUpdatedEvent.InputTuple, RiskParametersUpdatedEvent.OutputTuple, RiskParametersUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdraw(address,address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }