/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iQuickSwapRouterSol from './IQuickSwapRouter.sol/index.js';
export * as iSomiArbVaultSol from './ISomiArbVault.sol/index.js';
export * as iStandardClobSol from './IStandardCLOB.sol/index.js';