/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IStandardCLOB {
      
    export type MarketDataStruct = {lastPrice: BigNumberish, bestBid: BigNumberish, bestAsk: BigNumberish, volume24h: BigNumberish, priceChange24h: BigNumberish}

    export type MarketDataStructOutput = [lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint] & {lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint }
  

    export type OrderStruct = {id: BigNumberish, trader: AddressLike, baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, timestamp: BigNumberish, filled: BigNumberish, cancelled: boolean}

    export type OrderStructOutput = [id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean] & {id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean }
  
    }

  export interface IStandardCLOBInterface extends Interface {
    getFunction(nameOrSignature: "buyTokens" | "cancelOrder" | "fillOrder" | "getActiveOrders" | "getBestAsk" | "getBestBid" | "getLastPrice" | "getMarketData" | "getOrder" | "getOrderBook" | "getUserOrders" | "marketBuy" | "marketSell" | "placeOrder" | "sellTokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderCancelled" | "OrderFilled" | "OrderPlaced" | "Trade"): EventFragment;

    encodeFunctionData(functionFragment: 'buyTokens', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fillOrder', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveOrders', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBestAsk', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBestBid', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getLastPrice', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarketData', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrderBook', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserOrders', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'marketBuy', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketSell', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeOrder', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'sellTokens', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'buyTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestAsk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLastPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderBook', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sellTokens', data: BytesLike): Result;
  }

  
    export namespace OrderCancelledEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike];
      export type OutputTuple = [orderId: bigint, trader: string];
      export interface OutputObject {orderId: bigint, trader: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderFilledEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike, filledAmount: BigNumberish, price: BigNumberish];
      export type OutputTuple = [orderId: bigint, trader: string, filledAmount: bigint, price: bigint];
      export interface OutputObject {orderId: bigint, trader: string, filledAmount: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderPlacedEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike, baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean];
      export type OutputTuple = [orderId: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean];
      export interface OutputObject {orderId: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeEvent {
      export type InputTuple = [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, buyer: AddressLike, seller: AddressLike];
      export type OutputTuple = [baseToken: string, quoteToken: string, amount: bigint, price: bigint, buyer: string, seller: string];
      export interface OutputObject {baseToken: string, quoteToken: string, amount: bigint, price: bigint, buyer: string, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IStandardCLOB extends BaseContract {
    
    connect(runner?: ContractRunner | null): IStandardCLOB;
    waitForDeployment(): Promise<this>;

    interface: IStandardCLOBInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyTokens: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, minBaseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    cancelOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fillOrder: TypedContractMethod<
      [orderId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getActiveOrders: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getBestAsk: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >
    

    
    getBestBid: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >
    

    
    getLastPrice: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMarketData: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [IStandardCLOB.MarketDataStructOutput],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [IStandardCLOB.OrderStructOutput],
      'view'
    >
    

    
    getOrderBook: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint[], bigint[], bigint[], bigint[]] & {bidPrices: bigint[], bidAmounts: bigint[], askPrices: bigint[], askAmounts: bigint[] }],
      'view'
    >
    

    
    getUserOrders: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    marketBuy: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    marketSell: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    placeOrder: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    sellTokens: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, minQuoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyTokens'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, minBaseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fillOrder'): TypedContractMethod<
      [orderId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActiveOrders'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBestAsk'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getBestBid'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getLastPrice'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketData'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [IStandardCLOB.MarketDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [IStandardCLOB.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderBook'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint[], bigint[], bigint[], bigint[]] & {bidPrices: bigint[], bidAmounts: bigint[], askPrices: bigint[], askAmounts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserOrders'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'marketBuy'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketSell'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'placeOrder'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sellTokens'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, minQuoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'OrderCancelled'): TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
getEvent(key: 'OrderFilled'): TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
getEvent(key: 'OrderPlaced'): TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
getEvent(key: 'Trade'): TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;

    filters: {
      
      'OrderCancelled(uint256,address)': TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
      OrderCancelled: TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
    

      'OrderFilled(uint256,address,uint256,uint256)': TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
      OrderFilled: TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
    

      'OrderPlaced(uint256,address,address,address,uint256,uint256,bool)': TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
      OrderPlaced: TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
    

      'Trade(address,address,uint256,uint256,address,address)': TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
      Trade: TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
    
    };
  }