/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockErc20Sol from './MockERC20.sol/index.js';
export * as mockQuickSwapRouterSol from './MockQuickSwapRouter.sol/index.js';
export * as mockStandardClobSol from './MockStandardCLOB.sol/index.js';