/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc20Sol from './MockERC20.sol/index.js';
export type { mockErc20Sol };
import type * as mockQuickSwapRouterSol from './MockQuickSwapRouter.sol/index.js';
export type { mockQuickSwapRouterSol };
import type * as mockStandardClobSol from './MockStandardCLOB.sol/index.js';
export type { mockStandardClobSol };