/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IStandardCLOB {
      
    export type MarketDataStruct = {lastPrice: BigNumberish, bestBid: BigNumberish, bestAsk: BigNumberish, volume24h: BigNumberish, priceChange24h: BigNumberish}

    export type MarketDataStructOutput = [lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint] & {lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint }
  

    export type OrderStruct = {id: BigNumberish, trader: AddressLike, baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, timestamp: BigNumberish, filled: BigNumberish, cancelled: boolean}

    export type OrderStructOutput = [id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean] & {id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean }
  
    }

  export interface MockStandardCLOBInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "askAmountsStorage" | "askPricesStorage" | "bidAmountsStorage" | "bidPricesStorage" | "buyTokens" | "cancelOrder" | "fillOrder" | "fundCLOB" | "getActiveOrders" | "getBestAsk" | "getBestBid" | "getLastPrice" | "getMarketData" | "getOrder" | "getOrderBook" | "getUserOrders" | "marketBuy" | "marketDataStorage" | "marketSell" | "orders" | "placeOrder" | "sellTokens" | "setMarketPrice" | "userOrders"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderCancelled" | "OrderFilled" | "OrderPlaced" | "Trade"): EventFragment;

    encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'askAmountsStorage', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'askPricesStorage', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'bidAmountsStorage', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'bidPricesStorage', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyTokens', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fillOrder', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundCLOB', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveOrders', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBestAsk', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBestBid', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getLastPrice', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarketData', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrderBook', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserOrders', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'marketBuy', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketDataStorage', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'marketSell', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'orders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeOrder', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'sellTokens', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMarketPrice', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userOrders', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'askAmountsStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'askPricesStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bidAmountsStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bidPricesStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundCLOB', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestAsk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLastPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderBook', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketDataStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sellTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarketPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userOrders', data: BytesLike): Result;
  }

  
    export namespace OrderCancelledEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike];
      export type OutputTuple = [orderId: bigint, trader: string];
      export interface OutputObject {orderId: bigint, trader: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderFilledEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike, filledAmount: BigNumberish, price: BigNumberish];
      export type OutputTuple = [orderId: bigint, trader: string, filledAmount: bigint, price: bigint];
      export interface OutputObject {orderId: bigint, trader: string, filledAmount: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderPlacedEvent {
      export type InputTuple = [orderId: BigNumberish, trader: AddressLike, baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean];
      export type OutputTuple = [orderId: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean];
      export interface OutputObject {orderId: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeEvent {
      export type InputTuple = [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, buyer: AddressLike, seller: AddressLike];
      export type OutputTuple = [baseToken: string, quoteToken: string, amount: bigint, price: bigint, buyer: string, seller: string];
      export interface OutputObject {baseToken: string, quoteToken: string, amount: bigint, price: bigint, buyer: string, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockStandardCLOB extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockStandardCLOB;
    waitForDeployment(): Promise<this>;

    interface: MockStandardCLOBInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, bidPrice: BigNumberish, askPrice: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    askAmountsStorage: TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    askPricesStorage: TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    bidAmountsStorage: TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    bidPricesStorage: TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    buyTokens: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, minBaseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    cancelOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fillOrder: TypedContractMethod<
      [orderId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundCLOB: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getActiveOrders: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getBestAsk: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >
    

    
    getBestBid: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >
    

    
    getLastPrice: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMarketData: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [IStandardCLOB.MarketDataStructOutput],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [IStandardCLOB.OrderStructOutput],
      'view'
    >
    

    
    getOrderBook: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint[], bigint[], bigint[], bigint[]] & {bidPrices: bigint[], bidAmounts: bigint[], askPrices: bigint[], askAmounts: bigint[] }],
      'view'
    >
    

    
    getUserOrders: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    marketBuy: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    marketDataStorage: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint }],
      'view'
    >
    

    
    marketSell: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean, bigint, bigint, boolean] & {id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean }],
      'view'
    >
    

    
    placeOrder: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    sellTokens: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, minQuoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setMarketPrice: TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    userOrders: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, bidPrice: BigNumberish, askPrice: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'askAmountsStorage'): TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'askPricesStorage'): TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bidAmountsStorage'): TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bidPricesStorage'): TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyTokens'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, minBaseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fillOrder'): TypedContractMethod<
      [orderId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundCLOB'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActiveOrders'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBestAsk'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getBestBid'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint, bigint] & {price: bigint, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getLastPrice'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketData'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [IStandardCLOB.MarketDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [IStandardCLOB.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderBook'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, ],
      [[bigint[], bigint[], bigint[], bigint[]] & {bidPrices: bigint[], bidAmounts: bigint[], askPrices: bigint[], askAmounts: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserOrders'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'marketBuy'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, quoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketDataStorage'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {lastPrice: bigint, bestBid: bigint, bestAsk: bigint, volume24h: bigint, priceChange24h: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'marketSell'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean, bigint, bigint, boolean] & {id: bigint, trader: string, baseToken: string, quoteToken: string, amount: bigint, price: bigint, isBuy: boolean, timestamp: bigint, filled: bigint, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'placeOrder'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, amount: BigNumberish, price: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sellTokens'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, baseAmount: BigNumberish, minQuoteAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMarketPrice'): TypedContractMethod<
      [baseToken: AddressLike, quoteToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userOrders'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'OrderCancelled'): TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
getEvent(key: 'OrderFilled'): TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
getEvent(key: 'OrderPlaced'): TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
getEvent(key: 'Trade'): TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;

    filters: {
      
      'OrderCancelled(uint256,address)': TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
      OrderCancelled: TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
    

      'OrderFilled(uint256,address,uint256,uint256)': TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
      OrderFilled: TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
    

      'OrderPlaced(uint256,address,address,address,uint256,uint256,bool)': TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
      OrderPlaced: TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
    

      'Trade(address,address,uint256,uint256,address,address)': TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
      Trade: TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
    
    };
  }