/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace ISomiArbVault {
      
    export type ArbitrageParamsStruct = {tokenA: AddressLike, tokenB: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, expectedProfit: BigNumberish, minProfit: BigNumberish, slippage: BigNumberish, buyPlatform: BigNumberish, sellPlatform: BigNumberish, deadline: BigNumberish}

    export type ArbitrageParamsStructOutput = [tokenA: string, tokenB: string, amountIn: bigint, minAmountOut: bigint, expectedProfit: bigint, minProfit: bigint, slippage: bigint, buyPlatform: bigint, sellPlatform: bigint, deadline: bigint] & {tokenA: string, tokenB: string, amountIn: bigint, minAmountOut: bigint, expectedProfit: bigint, minProfit: bigint, slippage: bigint, buyPlatform: bigint, sellPlatform: bigint, deadline: bigint }
  
    }

  export interface ISomiArbVaultInterface extends Interface {
    getFunction(nameOrSignature: "deposit" | "executeArbitrage" | "getTotalValue" | "getUserBalance" | "getUserShares" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArbitrageExecuted" | "Deposit" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeArbitrage', values: [ISomiArbVault.ArbitrageParamsStruct]): string;
encodeFunctionData(functionFragment: 'getTotalValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserBalance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserShares', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeArbitrage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ArbitrageExecutedEvent {
      export type InputTuple = [tokenA: AddressLike, tokenB: AddressLike, amountIn: BigNumberish, profit: BigNumberish, buyPlatform: BigNumberish, sellPlatform: BigNumberish, executionId: BigNumberish];
      export type OutputTuple = [tokenA: string, tokenB: string, amountIn: bigint, profit: bigint, buyPlatform: bigint, sellPlatform: bigint, executionId: bigint];
      export interface OutputObject {tokenA: string, tokenB: string, amountIn: bigint, profit: bigint, buyPlatform: bigint, sellPlatform: bigint, executionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, amount: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, token: string, amount: bigint, shares: bigint];
      export interface OutputObject {user: string, token: string, amount: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, amount: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, token: string, amount: bigint, shares: bigint];
      export interface OutputObject {user: string, token: string, amount: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ISomiArbVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ISomiArbVault;
    waitForDeployment(): Promise<this>;

    interface: ISomiArbVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deposit: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    executeArbitrage: TypedContractMethod<
      [params: ISomiArbVault.ArbitrageParamsStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    getTotalValue: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserBalance: TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserShares: TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [token: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeArbitrage'): TypedContractMethod<
      [params: ISomiArbVault.ArbitrageParamsStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTotalValue'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBalance'): TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserShares'): TypedContractMethod<
      [user: AddressLike, token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [token: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'ArbitrageExecuted'): TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'ArbitrageExecuted(address,address,uint256,uint256,uint8,uint8,uint256)': TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
      ArbitrageExecuted: TypedContractEvent<ArbitrageExecutedEvent.InputTuple, ArbitrageExecutedEvent.OutputTuple, ArbitrageExecutedEvent.OutputObject>;
    

      'Deposit(address,address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Withdraw(address,address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }